# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'applicants.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#------------------
import sqlite3
import employer_page
from PyQt5.QtWidgets import *
#---------------------

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form9(object):
    def setupUi(self, Form9):
        Form9.setObjectName("Form9")
        Form9.resize(1522, 1022)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1500, 800))
        self.frame.setMaximumSize(QtCore.QSize(1500, 900))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tw1 = QtWidgets.QTableWidget(self.frame)
        self.tw1.setGeometry(QtCore.QRect(30, 170, 1441, 631))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tw1.setFont(font)
        self.tw1.setObjectName("tw1")
        self.tw1.setColumnCount(8)
        self.tw1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(7, item)
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(430, 40, 641, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("color: rgb(0, 0, 127);")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setGeometry(QtCore.QRect(670, 830, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form9)
        QtCore.QMetaObject.connectSlotsByName(Form9)

        #-------------------------------------
        self.tw1.setColumnWidth(0, 50)
        self.tw1.setColumnWidth(1, 150)
        self.tw1.setColumnWidth(2, 50)
        self.tw1.setColumnWidth(3, 300)
        self.tw1.setColumnWidth(4, 300)
        self.tw1.setColumnWidth(5, 150)
        self.tw1.setColumnWidth(6, 200)
        self.tw1.setColumnWidth(7, 200)

        self.b1.clicked.connect(self.fn)
        self.Form9=Form9
       
        
        db=sqlite3.connect('job_portal.db')
        s="select * from applicant"
        r=db.execute(s)
        
        self.tw1.setRowCount(0)             #clear the table widget
        for rowno,rec in enumerate(r):
            self.tw1.insertRow(rowno)
            for columnno,data in enumerate(rec):
                self.tw1.setItem(rowno,columnno,QTableWidgetItem(str(data)))
                
                
        db.close()

        self.tw1.verticalHeader().setVisible(False)


        st = "::section {background-color: rgb(200,200,255);font-size:14px;font-weight:bold; }"
        self.tw1.horizontalHeader().setStyleSheet( st )

    def fn(self):
        self.Form8 = QtWidgets.QWidget()
        self.ui = employer_page.Ui_Form8()
        self.ui.setupUi(self.Form8)
        self.Form9.close()
        self.Form8.show()

       #----------------------------

        

    def retranslateUi(self, Form9):
        _translate = QtCore.QCoreApplication.translate
        Form9.setWindowTitle(_translate("Form9", "Applicants"))
        item = self.tw1.horizontalHeaderItem(0)
        item.setText(_translate("Form9", "a_id"))
        item = self.tw1.horizontalHeaderItem(1)
        item.setText(_translate("Form9", "Name"))
        item = self.tw1.horizontalHeaderItem(2)
        item.setText(_translate("Form9", "Age"))
        item = self.tw1.horizontalHeaderItem(3)
        item.setText(_translate("Form9", "Mail"))
        item = self.tw1.horizontalHeaderItem(4)
        item.setText(_translate("Form9", "Qualification"))
        item = self.tw1.horizontalHeaderItem(5)
        item.setText(_translate("Form9", "Contact"))
        item = self.tw1.horizontalHeaderItem(6)
        item.setText(_translate("Form9", "Required Job"))
        item = self.tw1.horizontalHeaderItem(7)
        item.setText(_translate("Form9", "Company"))
        self.l1.setText(_translate("Form9", "List of Applicants"))
        self.b1.setText(_translate("Form9", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form9 = QtWidgets.QWidget()
    ui = Ui_Form9()
    ui.setupUi(Form9)
    Form9.show()
    sys.exit(app.exec_())
