# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employee_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#-----------------------
import employee_page
import sqlite3
from PyQt5.QtWidgets import *
#------------------------


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form3):
        Form3.setObjectName("Form3")
        Form3.resize(1125, 837)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1000, 800))
        self.frame.setMaximumSize(QtCore.QSize(1000, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(150, 140, 711, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("color: rgb(0, 0, 127);")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.frame)
        self.l2.setGeometry(QtCore.QRect(300, 320, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.le1 = QtWidgets.QLineEdit(self.frame)
        self.le1.setGeometry(QtCore.QRect(460, 330, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.le1.setFont(font)
        self.le1.setText("")
        self.le1.setObjectName("le1")
        self.l3 = QtWidgets.QLabel(self.frame)
        self.l3.setGeometry(QtCore.QRect(300, 430, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setObjectName("l3")
        self.le2 = QtWidgets.QLineEdit(self.frame)
        self.le2.setGeometry(QtCore.QRect(460, 440, 311, 41))
        self.le2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le2.setObjectName("le2")
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setGeometry(QtCore.QRect(440, 540, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form3)
        QtCore.QMetaObject.connectSlotsByName(Form3)

        #---------------------------
        self.b1.clicked.connect(self.fn1)
        self.Form3=Form3
        
    def fn1(self):
        a = self.le1.text()
        b = self.le2.text()
        db = sqlite3.connect('job_portal.db')
        cursor = db.cursor()  # Create cursor object

        cursor.execute("SELECT COUNT(*) FROM employee_login WHERE username = ? AND password = ?", (a, b))
        count = cursor.fetchone()[0]

        if count > 0:
            self.Form5 = QtWidgets.QWidget()
            self.ui = employee_page.Ui_Form5()
            self.ui.setupUi(self.Form5)
            self.Form3.close()
            self.Form5.show()
        else:
            QMessageBox.critical(self.Form3, "ERROR", "Invalid username or password")

    
        #---------------------------

    def retranslateUi(self, Form3):
        _translate = QtCore.QCoreApplication.translate
        Form3.setWindowTitle(_translate("Form3", "Employee login"))
        self.l1.setText(_translate("Form3", "Employee Login"))
        self.l2.setText(_translate("Form3", "Username"))
        self.l3.setText(_translate("Form3", "Password"))
        self.b1.setText(_translate("Form3", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form3 = QtWidgets.QWidget()
    ui = Ui_Form3()
    ui.setupUi(Form3)
    Form3.show()
    sys.exit(app.exec_())
