# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employer_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#---------------------
import applicants
import update
#---------------------

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form8(object):
    def setupUi(self, Form8):
        Form8.setObjectName("Form8")
        Form8.resize(1140, 854)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1000, 800))
        self.frame.setMaximumSize(QtCore.QSize(1000, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(220, 130, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.frame)
        self.l2.setGeometry(QtCore.QRect(220, 440, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setGeometry(QtCore.QRect(390, 220, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.frame)
        self.b2.setGeometry(QtCore.QRect(390, 520, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form8)
        QtCore.QMetaObject.connectSlotsByName(Form8)

        #----------------------
        self.b1.clicked.connect(self.fn1)
        self.b2.clicked.connect(self.fn2)
        self.Form8=Form8

    def fn1(self):
        self.Form9 = QtWidgets.QWidget()
        self.ui = applicants.Ui_Form9()
        self.ui.setupUi(self.Form9)
        self.Form8.close()
        self.Form9.show()

    def fn2(self):
        self.Form10 = QtWidgets.QWidget()
        self.ui = update.Ui_Form10()
        self.ui.setupUi(self.Form10)
        self.Form8.close()
        self.Form10.show()
        

    def retranslateUi(self, Form8):
        _translate = QtCore.QCoreApplication.translate
        Form8.setWindowTitle(_translate("Form8", "Employer Page"))
        self.l1.setText(_translate("Form8", "View the Applicants"))
        self.l2.setText(_translate("Form8", "Update the Job Listings"))
        self.b1.setText(_translate("Form8", "Applicants"))
        self.b2.setText(_translate("Form8", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form8 = QtWidgets.QWidget()
    ui = Ui_Form8()
    ui.setupUi(Form8)
    Form8.show()
    sys.exit(app.exec_())
