# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employee_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#-----------------------
import job_listings
import apply
import sqlite3
from PyQt5.QtWidgets import *
#------------------------

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form5(object):
    def setupUi(self, Form5):
        Form5.setObjectName("Form5")
        Form5.resize(1822, 875)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1600, 800))
        self.frame.setMaximumSize(QtCore.QSize(1600, 800))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setGeometry(QtCore.QRect(400, 700, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.frame)
        self.b2.setGeometry(QtCore.QRect(810, 700, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.l2 = QtWidgets.QLabel(self.frame)
        self.l2.setGeometry(QtCore.QRect(340, 50, 231, 241))
        self.l2.setText("")
        self.l2.setPixmap(QtGui.QPixmap("E:/images.png"))
        self.l2.setScaledContents(True)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.frame)
        self.l3.setGeometry(QtCore.QRect(670, 50, 231, 241))
        self.l3.setText("")
        self.l3.setPixmap(QtGui.QPixmap("E:/Amazon-logo-meaning.jpg"))
        self.l3.setScaledContents(True)
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.frame)
        self.l4.setGeometry(QtCore.QRect(1000, 50, 231, 241))
        self.l4.setText("")
        self.l4.setPixmap(QtGui.QPixmap("E:/owuT8U7P_400x400.jpg"))
        self.l4.setScaledContents(True)
        self.l4.setObjectName("l4")
        self.l7 = QtWidgets.QLabel(self.frame)
        self.l7.setGeometry(QtCore.QRect(340, 370, 231, 241))
        self.l7.setText("")
        self.l7.setPixmap(QtGui.QPixmap("E:/images (2).png"))
        self.l7.setScaledContents(True)
        self.l7.setObjectName("l7")
        self.l8 = QtWidgets.QLabel(self.frame)
        self.l8.setGeometry(QtCore.QRect(670, 370, 231, 241))
        self.l8.setText("")
        self.l8.setPixmap(QtGui.QPixmap("E:/download.png"))
        self.l8.setScaledContents(True)
        self.l8.setObjectName("l8")
        self.l9 = QtWidgets.QLabel(self.frame)
        self.l9.setGeometry(QtCore.QRect(1000, 370, 231, 241))
        self.l9.setText("")
        self.l9.setPixmap(QtGui.QPixmap("E:/images (1).png"))
        self.l9.setScaledContents(True)
        self.l9.setObjectName("l9")
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(10, 50, 231, 241))
        self.l1.setText("")
        self.l1.setPixmap(QtGui.QPixmap("E:/download (1).png"))
        self.l1.setScaledContents(True)
        self.l1.setObjectName("l1")
        self.l5 = QtWidgets.QLabel(self.frame)
        self.l5.setGeometry(QtCore.QRect(1320, 50, 231, 241))
        self.l5.setText("")
        self.l5.setPixmap(QtGui.QPixmap("E:/images (3).png"))
        self.l5.setScaledContents(True)
        self.l5.setObjectName("l5")
        self.l6 = QtWidgets.QLabel(self.frame)
        self.l6.setGeometry(QtCore.QRect(10, 370, 231, 241))
        self.l6.setText("")
        self.l6.setPixmap(QtGui.QPixmap("E:/download.jpeg"))
        self.l6.setScaledContents(True)
        self.l6.setObjectName("l6")
        self.l10 = QtWidgets.QLabel(self.frame)
        self.l10.setGeometry(QtCore.QRect(1320, 370, 231, 241))
        self.l10.setText("")
        self.l10.setPixmap(QtGui.QPixmap("E:/download (2).png"))
        self.l10.setScaledContents(True)
        self.l10.setObjectName("l10")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form5)
        QtCore.QMetaObject.connectSlotsByName(Form5)

        #------------------------
        self.b1.clicked.connect(self.fn1)
        self.b2.clicked.connect(self.fn2)
        self.Form5=Form5
        
    def fn1(self):
        self.Form6 = QtWidgets.QWidget()
        self.ui = job_listings.Ui_Form6()
        self.ui.setupUi(self.Form6)
        self.Form5.close()
        self.Form6.show()

    def fn2(self):
        self.Form7 = QtWidgets.QWidget()
        self.ui = apply.Ui_Form7()
        self.ui.setupUi(self.Form7)
        self.Form5.close()
        self.Form7.show()

        #------------------------

    def retranslateUi(self, Form5):
        _translate = QtCore.QCoreApplication.translate
        Form5.setWindowTitle(_translate("Form5", "Employee Page"))
        self.b1.setText(_translate("Form5", "Job Listings"))
        self.b2.setText(_translate("Form5", "Apply for job"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form5 = QtWidgets.QWidget()
    ui = Ui_Form5()
    ui.setupUi(Form5)
    Form5.show()
    sys.exit(app.exec_())
