# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.




#---------------------
import login
#---------------------

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(1622, 942)
        Form1.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1600, 800))
        self.frame.setMaximumSize(QtCore.QSize(1600, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 160, 651, 581))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:/pexels-shkrabaanthony-4348401.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(0, 0, 511, 151))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(58)
        font.setBold(False)
        font.setWeight(50)
        self.l1.setFont(font)
        self.l1.setStyleSheet("color: rgb(0, 0, 127);")
        self.l1.setObjectName("l1")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(780, 160, 711, 491))
        font = QtGui.QFont()
        font.setFamily("Calisto MT")
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setGeometry(QtCore.QRect(1050, 690, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

        #---------------------------
        self.b1.clicked.connect(self.fn1)
        self.Form1=Form1

    def fn1(self):
        self.Form2 = QtWidgets.QWidget()
        self.ui = login.Ui_Form2()
        self.ui.setupUi(self.Form2)
        self.Form1.close()
        self.Form2.show()

        #---------------------------    
                        

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Homepage"))
        self.l1.setText(_translate("Form1", "Job Portal"))
        self.plainTextEdit.setPlainText(_translate("Form1", "    Welcome to our Job Portal, your gateway to limitless career opportunities! Our job portal is a dynamic platform designed to connect talented individuals with their dream careers and empower employers to find the perfect fit for their teams.\n"
"\n"
"    Discover a comprehensive range of job listings spanning industries, roles, and experience levels, ensuring there\'s something for everyone. Our intuitive search and filter features streamline the job search process, allowing candidates to pinpoint opportunities that match their skills, interests, and location preferences with ease.\n"
"\n"
"    For employers, our robust recruitment tools offer unparalleled efficiency in sourcing, screening, and hiring top talent. From posting job vacancies to managing applications and conducting interviews, our platform simplifies every step of the hiring process, saving valuable time and resources.\n"
"\n"
"    Whether you\'re a seasoned professional seeking new challenges or an employer looking to build a stellar team, Job Portal is your trusted partner in shaping a brighter future. Join our community today and take the next step towards success!"))
        self.b1.setText(_translate("Form1", "LOGIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form1 = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form1)
    Form1.show()
    sys.exit(app.exec_())
