# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_listings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#--------------------
import sqlite3
import employee_page
from PyQt5.QtWidgets import *
#--------------------

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form6(object):
    def setupUi(self, Form6):
        Form6.setObjectName("Form6")
        Form6.resize(1522, 1022)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1500, 900))
        self.frame.setMaximumSize(QtCore.QSize(1500, 900))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(340, 10, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.le1 = QtWidgets.QLineEdit(self.frame)
        self.le1.setGeometry(QtCore.QRect(590, 20, 321, 41))
        self.le1.setObjectName("le1")
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setGeometry(QtCore.QRect(970, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.tw1 = QtWidgets.QTableWidget(self.frame)
        self.tw1.setGeometry(QtCore.QRect(0, 110, 1501, 691))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tw1.setFont(font)
        self.tw1.setObjectName("tw1")
        self.tw1.setColumnCount(6)
        self.tw1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw1.setHorizontalHeaderItem(5, item)
        self.b2 = QtWidgets.QPushButton(self.frame)
        self.b2.setGeometry(QtCore.QRect(670, 830, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form6)
        QtCore.QMetaObject.connectSlotsByName(Form6)

        #--------------------------------
        self.tw1.setColumnWidth(0, 118)
        self.tw1.setColumnWidth(1, 300)
        self.tw1.setColumnWidth(2, 180)
        self.tw1.setColumnWidth(3, 300)
        self.tw1.setColumnWidth(4, 300)
        self.tw1.setColumnWidth(5, 300)

        st = "::section {background-color: rgb(147,208,244); }"
        self.tw1.horizontalHeader().setStyleSheet(st)

        self.b1.clicked.connect(self.fn1)
        self.b2.clicked.connect(self.fn2)
        self.Form6=Form6

    def fn1(self):
        a = self.le1.text()
        db = sqlite3.connect('job_portal.db')
        s = "select * from job_listings where title='" + a + "'"

        r = db.execute(s)

        self.tw1.setRowCount(0)  # clear the table rows

        for rowno, row in enumerate(r):
            self.tw1.insertRow(rowno)
            for columnno, data in enumerate(row):
                self.tw1.setItem(rowno, columnno, QTableWidgetItem(str(data)))

        db.close()
        self.tw1.verticalHeader().setVisible(False)

    def fn2(self):
        self.Form5 = QtWidgets.QWidget()
        self.ui = employee_page.Ui_Form5()
        self.ui.setupUi(self.Form5)
        self.Form6.close()
        self.Form5.show()
        
        #--------------------------------
        

    def retranslateUi(self, Form6):
        _translate = QtCore.QCoreApplication.translate
        Form6.setWindowTitle(_translate("Form6", "Job Listings"))
        self.l1.setText(_translate("Form6", "Search for a job"))
        self.b1.setText(_translate("Form6", "Search"))
        item = self.tw1.horizontalHeaderItem(0)
        item.setText(_translate("Form6", "Job_id"))
        item = self.tw1.horizontalHeaderItem(1)
        item.setText(_translate("Form6", "Title"))
        item = self.tw1.horizontalHeaderItem(2)
        item.setText(_translate("Form6", "Salary"))
        item = self.tw1.horizontalHeaderItem(3)
        item.setText(_translate("Form6", "Experience"))
        item = self.tw1.horizontalHeaderItem(4)
        item.setText(_translate("Form6", "Company"))
        item = self.tw1.horizontalHeaderItem(5)
        item.setText(_translate("Form6", "Location"))
        self.b2.setText(_translate("Form6", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form6 = QtWidgets.QWidget()
    ui = Ui_Form6()
    ui.setupUi(Form6)
    Form6.show()
    sys.exit(app.exec_())
