# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#-------------------
import sqlite3
import homepage
from PyQt5.QtWidgets import *
#-------------------

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form10(object):
    def setupUi(self, Form10):
        Form10.setObjectName("Form10")
        Form10.resize(1148, 922)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1000, 900))
        self.frame.setMaximumSize(QtCore.QSize(1000, 900))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(180, 10, 641, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("color: rgb(0, 0, 127);")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.le1 = QtWidgets.QLineEdit(self.frame)
        self.le1.setGeometry(QtCore.QRect(440, 160, 271, 41))
        self.le1.setObjectName("le1")
        self.le2 = QtWidgets.QLineEdit(self.frame)
        self.le2.setGeometry(QtCore.QRect(440, 240, 271, 41))
        self.le2.setObjectName("le2")
        self.le3 = QtWidgets.QLineEdit(self.frame)
        self.le3.setGeometry(QtCore.QRect(440, 320, 271, 41))
        self.le3.setObjectName("le3")
        self.le4 = QtWidgets.QLineEdit(self.frame)
        self.le4.setGeometry(QtCore.QRect(440, 390, 271, 41))
        self.le4.setObjectName("le4")
        self.le5 = QtWidgets.QLineEdit(self.frame)
        self.le5.setGeometry(QtCore.QRect(440, 470, 271, 41))
        self.le5.setObjectName("le5")
        self.le6 = QtWidgets.QLineEdit(self.frame)
        self.le6.setGeometry(QtCore.QRect(440, 550, 271, 41))
        self.le6.setObjectName("le6")
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setGeometry(QtCore.QRect(750, 160, 121, 41))
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.frame)
        self.b2.setGeometry(QtCore.QRect(210, 680, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.frame)
        self.b3.setGeometry(QtCore.QRect(440, 680, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.frame)
        self.b4.setGeometry(QtCore.QRect(670, 680, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(280, 150, 131, 451))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.verticalLayout.addWidget(self.l2)
        self.l3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setObjectName("l3")
        self.verticalLayout.addWidget(self.l3)
        self.l4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l4.setFont(font)
        self.l4.setObjectName("l4")
        self.verticalLayout.addWidget(self.l4)
        self.l5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l5.setFont(font)
        self.l5.setObjectName("l5")
        self.verticalLayout.addWidget(self.l5)
        self.l6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l6.setFont(font)
        self.l6.setObjectName("l6")
        self.verticalLayout.addWidget(self.l6)
        self.l7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l7.setFont(font)
        self.l7.setObjectName("l7")
        self.verticalLayout.addWidget(self.l7)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form10)
        QtCore.QMetaObject.connectSlotsByName(Form10)

        #1---------------------------------

        self.b1.clicked.connect(self.fn1)
        self.b2.clicked.connect(self.fn2)
        self.b3.clicked.connect(self.fn3)
        self.b4.clicked.connect(self.fn4)

        self.Form10=Form10
        
        self.b2.setEnabled(False)
        self.b3.setEnabled(False)
        
    def fn1(self):
        a=self.le1.text()
        db=sqlite3.connect('job_portal.db')
        s="select * from job_listings where job_id="+a+""
        
        r=db.execute (s)
        reclist=r.fetchall()

        if len(reclist)==0:
            self.b2.setEnabled(False)
            self.b3.setEnabled(False)

            QMessageBox.critical(self.Form10, "Error", "Invalid job_ID.")

            self.le2.clear()
            self.le3.clear()
            self.le4.clear()
            self.le5.clear()
            self.le6.clear()

        else:

            self.le2.setText(str(reclist[0] [1]))
            self.le3.setText(str(reclist[0][2]))
            self.le4.setText(str(reclist [0][3]))
            self.le5.setText(str(reclist [0][4]))
            self.le6.setText(str(reclist [0][5]))

            self.b2.setEnabled(True)
            self.b3.setEnabled(True)

        #2---------------------------------
            
    def fn2(self):
        a=self.le1.text()
        b=self.le2.text()
        c=self.le3.text()
        d=self.le4.text()
        e=self.le5.text()
        f=self.le6.text()
        
        
        db=sqlite3.connect('job_portal.db')
        s="update job_listings set title='"+b+"', salary="+c+",experience='"+d+"',company='"+e+"',location='"+f+"' where job_id="+a+""
        db.execute(s)
        db.commit()
        QMessageBox.about(self.Form10,"Updation","Record updated successfully.")
        
        self.le1.clear()
        self.le2.clear()
        self.le3.clear()
        self.le4.clear()
        self.le5.clear()
        self.le6.clear()
        
        db.close()
        self.b2.setEnabled(False)
        self.b3.setEnabled(False)

            
        #3--------------------------------
        
    def fn3(self):
        a=self.le1.text()
        db=sqlite3.connect('job_portal.db')
        s="delete from job_listings where job_id="+a+""
        
        db.execute(s)
        db.commit()
        
        QMessageBox.about(self.Form10,"Deleted","Record deleted successfully.")
        self.le1.clear()
        self.le2.clear()
        self.le3.clear()
        self.le4.clear()
        self.le5.clear()
        self.le6.clear()
        
        self.b2.setEnabled(False)
        self.b3.setEnabled(False)
        db.close()
        
        #4---------------------------------
    def fn4(self):
        self.Form1 = QtWidgets.QWidget()
        self.ui = homepage.Ui_Form1()
        self.ui.setupUi(self.Form1)
        self.Form10.close()
        self.Form1.show()
        
        #---------------------------------



    def retranslateUi(self, Form10):
        _translate = QtCore.QCoreApplication.translate
        Form10.setWindowTitle(_translate("Form10", "Update"))
        self.l1.setText(_translate("Form10", "Update Job Listings"))
        self.b1.setText(_translate("Form10", "Find"))
        self.b2.setText(_translate("Form10", "Update"))
        self.b3.setText(_translate("Form10", "Delete"))
        self.b4.setText(_translate("Form10", "Logout"))
        self.l2.setText(_translate("Form10", "Job_id"))
        self.l3.setText(_translate("Form10", "Title"))
        self.l4.setText(_translate("Form10", "Salary"))
        self.l5.setText(_translate("Form10", "Experience"))
        self.l6.setText(_translate("Form10", "Company"))
        self.l7.setText(_translate("Form10", "Location"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form10 = QtWidgets.QWidget()
    ui = Ui_Form10()
    ui.setupUi(Form10)
    Form10.show()
    sys.exit(app.exec_())
